# Generated by Django 5.2.7 on 2025-10-14 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_description',
            field=models.TextField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.ImageField(default='images/deafult.jpg', upload_to='images/'),
        ),
    ]
