# Generated by Django 5.2.7 on 2025-10-15 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='categories',
            field=models.ManyToManyField(default='other', related_name='items', to='main_app.category'),
        ),
    ]
