# Generated by Django 5.2.7 on 2025-10-15 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_item_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='categories',
            field=models.ManyToManyField(null=True, related_name='items', to='main_app.category'),
        ),
    ]
